{% set name = "napari-assistant" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8b05bd132e018657ec191fc12c999e6be43ad736f00d590493eeafba4ea00fa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - naparia = napari_assistant:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
  run:
    - loguru
    - magicgui
    - napari >=0.4.14
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.2.0
    - napari-time-slicer >=0.4.0
    - napari-workflows >=0.2.10
    - numpy !=1.19.4
    - pyperclip
    - python >={{ python_min }},<3.11
    - scikit-image
    - toolz
    - typing_extensions
    - qtpy
    - pyqt

test:
  imports:
    - napari_assistant
  commands:
    - pip list
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-assistant
  summary: A pocket calculator like interface to image processing in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
