{% set name = "napari-assistant" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6fdbe8bbe45f04383e2c7e6999e2fd01ccb9ca3077aac5febb7a19e31ca650bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - naparia = napari_assistant:main

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - loguru
    - magicgui
    - napari >=0.4.14
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.2.0
    - napari-time-slicer >=0.4.0
    - napari-workflows >=0.2.10
    - numpy !=1.19.4
    - pyperclip
    - python >=3.6, <3.11
    - scikit-image
    - toolz
    - typing_extensions
    - qtpy
    - pyqt

test:
  imports:
    - napari_assistant
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-assistant
  summary: A pocket calculator like interface to image processing in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
